#!/bin/sh
set -e

case "$1" in
    configure)
        systemctl daemon-reload
        systemctl enable hsa-snoop-prometheus.service
        systemctl start hsa-snoop-prometheus.service || true
        ;;
esac

exit 0
