name: spell-check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - 'feat/**'
    paths:
      - '**.md'
      - '.wordlist.txt'
      - '.spellcheck.yml'
      - '.github/workflows/spell-check.yml'

jobs:
  spell-check:
    name: spell-check for hsa-snoop
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: GitHub Spellcheck Action
      uses: rojopolis/spellcheck-github-actions@0.52.0
